# TASK 2 (Machine Learning)
## Prediction of CTC/Salary of new hires using Linear Regression

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
trainData=pd.read_excel('Data_file.xlsx',skiprows=[0,1])

In [3]:
trainData.head()

S.No. College       Role  City type  Previous CTC  Previous job changes  \
0      1  Tier 1    Manager  Non-Metro         55523                     3   
1      2  Tier 2  Executive      Metro         57081                     1   
2      3  Tier 2  Executive      Metro         60347                     2   
3      4  Tier 3  Executive      Metro         49010                     2   
4      5  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp (Months)           CTC  
0                66            19  71406.576531  
1                84            18  68005.870631  
2                52            28  76764.020277  
3                81            33  82092.386880  
4                74            32  73878.097729

In [4]:
trainData.drop('S.No.',axis=1,inplace=True)
trainData.rename(columns={'Exp (Months)':'Exp'},inplace=True)

In [5]:
trainData.head()

College       Role  City type  Previous CTC  Previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp           CTC  
0                66   19  71406.576531  
1                84   18  68005.870631  
2                52   28  76764.020277  
3                81   33  82092.386880  
4                74   32  73878.097729

In [6]:
trainData.shape

(1338, 8)

In [9]:
trainData.isnull().sum()

College                 0
Role                    0
City type               0
Previous CTC            0
Previous job changes    0
Graduation marks        0
Exp                     0
CTC                     0
dtype: int64

In [10]:
trainData.dtypes

College                  object
Role                     object
City type                object
Previous CTC              int64
Previous job changes      int64
Graduation marks          int64
Exp                       int64
CTC                     float64
dtype: object

In [11]:
X=trainData.drop('CTC',axis='columns')

In [12]:
X.head()

College       Role  City type  Previous CTC  Previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp  
0                66   19  
1                84   18  
2                52   28  
3                81   33  
4                74   32

OneHotEncoding

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
column_trans=make_column_transformer((OneHotEncoder(),['College', 'Role', 'City type']),remainder='passthrough')

In [14]:
X_encoded=column_trans.fit_transform(X)

In [15]:
X_encoded

array([[ 1.,  0.,  0., ...,  3., 66., 19.],
       [ 0.,  1.,  0., ...,  1., 84., 18.],
       [ 0.,  1.,  0., ...,  2., 52., 28.],
       ...,
       [ 0.,  1.,  0., ...,  1., 47., 18.],
       [ 1.,  0.,  0., ...,  3., 69., 21.],
       [ 0.,  0.,  1., ...,  1., 47., 61.]])

Scaling the Data

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler=StandardScaler()

In [18]:
X_scaled=scaler.fit_transform(X_encoded)

In [19]:
X_scaled

array([[ 1.0303559 , -0.61132367, -0.56641788, ...,  0.42257741,
         0.4103073 , -1.43876426],
       [-0.97053843,  1.63579466, -0.56641788, ..., -1.35823699,
         1.61924306, -1.50996545],
       [-0.97053843,  1.63579466, -0.56641788, ..., -0.46782979,
        -0.52997607, -0.79795355],
       ...,
       [-0.97053843,  1.63579466, -0.56641788, ..., -1.35823699,
        -0.86579156, -1.50996545],
       [ 1.0303559 , -0.61132367, -0.56641788, ...,  0.42257741,
         0.61179659, -1.29636188],
       [-0.97053843, -0.61132367,  1.76548098, ..., -1.35823699,
        -0.86579156,  1.55168573]])

In [20]:
y=trainData.loc[:,'CTC']

In [21]:
y

0       71406.576531
1       68005.870631
2       76764.020277
3       82092.386880
4       73878.097729
            ...     
1333    69712.403655
1334    69298.750099
1335    66397.770686
1336    64044.382949
1337    83346.060961
Name: CTC, Length: 1338, dtype: float64

Training the Model

In [22]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [23]:
model.fit(X_scaled,y)

LinearRegression()

TEST DATA

In [24]:
testData=pd.read_excel('Test_data_file.xlsx', usecols=['College','Role','City type','previous CTC','previous job changes','Graduation marks','Exp','Actual CTC'])

In [25]:
testData.head()

College       Role  City type  previous CTC  previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp    Actual CTC  
0                66   19  71406.576531  
1                84   18  68005.870631  
2                52   28  76764.020277  
3                81   33  82092.386880  
4                74   32  73878.097729

In [26]:
testData.rename(columns={'previous CTC':'Previous CTC','previous job changes':'Previous job changes','Actual CTC':'CTC'},inplace=True)

In [27]:
testData.head()

College       Role  City type  Previous CTC  Previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp           CTC  
0                66   19  71406.576531  
1                84   18  68005.870631  
2                52   28  76764.020277  
3                81   33  82092.386880  
4                74   32  73878.097729

In [28]:
testData.isnull().sum()

College                 0
Role                    0
City type               0
Previous CTC            0
Previous job changes    0
Graduation marks        0
Exp                     0
CTC                     0
dtype: int64

In [29]:
Xtest=testData.drop('CTC',axis='columns')

In [30]:
Xtest.head()

College       Role  City type  Previous CTC  Previous job changes  \
0  Tier 1    Manager  Non-Metro         55523                     3   
1  Tier 2  Executive      Metro         57081                     1   
2  Tier 2  Executive      Metro         60347                     2   
3  Tier 3  Executive      Metro         49010                     2   
4  Tier 3  Executive      Metro         57879                     4   

   Graduation marks  Exp  
0                66   19  
1                84   18  
2                52   28  
3                81   33  
4                74   32

OneHotEncoding

In [35]:
Xtest_encoded=column_trans.transform(Xtest)

In [36]:
Xtest_encoded

array([[ 1.,  0.,  0., ...,  3., 66., 19.],
       [ 0.,  1.,  0., ...,  1., 84., 18.],
       [ 0.,  1.,  0., ...,  2., 52., 28.],
       ...,
       [ 0.,  1.,  0., ...,  1., 47., 18.],
       [ 1.,  0.,  0., ...,  3., 69., 21.],
       [ 0.,  0.,  1., ...,  1., 47., 61.]])

Scaling the Data

In [37]:
Xtest_scaled=scaler.transform(Xtest_encoded)

In [38]:
Xtest_scaled

array([[ 1.0303559 , -0.61132367, -0.56641788, ...,  0.42257741,
         0.4103073 , -1.43876426],
       [-0.97053843,  1.63579466, -0.56641788, ..., -1.35823699,
         1.61924306, -1.50996545],
       [-0.97053843,  1.63579466, -0.56641788, ..., -0.46782979,
        -0.52997607, -0.79795355],
       ...,
       [-0.97053843,  1.63579466, -0.56641788, ..., -1.35823699,
        -0.86579156, -1.50996545],
       [ 1.0303559 , -0.61132367, -0.56641788, ...,  0.42257741,
         0.61179659, -1.29636188],
       [-0.97053843, -0.61132367,  1.76548098, ..., -1.35823699,
        -0.86579156,  1.55168573]])

In [39]:
ytest=testData.loc[:,'CTC']

In [40]:
ytest

0       71406.576531
1       68005.870631
2       76764.020277
3       82092.386880
4       73878.097729
            ...     
1333    69712.403655
1334    69298.750099
1335    66397.770686
1336    64044.382949
1337    83346.060961
Name: CTC, Length: 1338, dtype: float64

PREDICTIONS

In [41]:
y1=model.predict(Xtest_scaled)

In [42]:
y1

array([86443.5328265, 65859.5328265, 70043.5328265, ..., 64107.5328265,
       66507.5328265, 90795.5328265])

In [43]:
score=model.score(Xtest_scaled,ytest)

In [44]:
score

0.6080065920664453

In [45]:
from sklearn.metrics import mean_squared_error

In [46]:
mean_squared_error(y,y1)

61706386.05417304

In [47]:
from sklearn.metrics import mean_absolute_error

In [50]:
mean_absolute_error(y,y1)

6158.833294403711